---
env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - jest
  - import
rules:
  no-console: warn
  prettier/prettier: error
  no-shadow: error
  eqeqeq:
    - error
    - always
  curly:
    - error
    - all
  no-unused-vars: warn
  no-redeclare: error
  prefer-const: error
  no-var: error
  global-require: warn
  handle-callback-err: warn
  no-buffer-constructor: warn
  no-new-require: warn
  no-path-concat: warn
settings:
  react:
    version: detect

overrides:
  - files:
      - '*.d.ts'
    rules:
      'no-unused-vars': 'off'
      'prettier/prettier': 'off'
