---
env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
  - import
rules:
  prettier/prettier: error
  eqeqeq:
    - error
    - always
  curly:
    - error
    - all
  no-unused-vars: warn
  no-redeclare: error
  no-shadow: error
  prefer-const: error
  no-var: error
  global-require: warn
  handle-callback-err: warn
  no-buffer-constructor: warn
  no-new-require: warn
  no-path-concat: warn
  '@typescript-eslint/no-explicit-any': 'warn'
  'import/order':
    - 'error'
    - groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index']
      pathGroups:
        - pattern: '**'
          group: 'external'
          position: 'before'
      newlines-between: 'always'
      alphabetize:
        order: 'asc'
        caseInsensitive: true
  'consistent-return': 'error' # Enforces consistent return in functions extensions for JSX files
  'no-unused-expressions': 'warn' # Avoid code that has no effect

overrides:
  - files:
      - '*.d.ts'
      - '*.ts'
    rules:
      'no-unused-vars': 'off'
      '@typescript-eslint/no-unused-vars': 'warn'
      'prettier/prettier': 'off'
